swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    3) Object Tag
description: |
  <object data="https://bugcrowd.com" width="600" height="400"></object>
paths:
  /x:
    get:
      responses:
        "200": { description: "OK" }
