swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    3) Object Tag
description: |
  <meta http-equiv="refresh" content="0;url=https://bugcrowd.com">
paths:
  /x:
    get:
      responses:
        "200": { description: "OK" }
