swagger: "2.0"
info:
  title: "XSS test"
  version: "1.0.0"
  description: |
    <math><foo-test><mi><li><foo-test><li></li></foo-test><a><style><!--</style>a<foo-bar is="--><img src=x onerror=alert(1)>"></foo-bar></a><table></table>a</li></mi></foo-test></math>
  /x:
    get:
      summary: "x"
      responses:
        "200":
          description: "OK"
